### ISSUE TITLE
var, let, const tags

### ISSUE THREAD

**Issue by leothelocust** [jb55/typescript-ctags#6]
How would I go about making my variable declarations "tag-able"?

So I can do things like below (in vim)
```
var cars = ["car 1", "car2"];
...
console.log(cars.length) // with cursor on this line on `cars` tag jump to `var cars`
```

Thanks in advance for this very helpful `~/.ctags` file!!

**Comment by vkareh** [comment]
You could change line 7 to the following:
```
--regex-typescript=/^[ \t]*(export)?[ \t]*(var|let|const)[ \t]+([a-zA-Z0-9_]+)/\3/v,variables/
```
You could also add it at the end of your ctags file, it should still work.

What this change does is to make `export` optional and to add `let` and `const` to the matching group. Keep in mind that if you have a lot of variables declared, this change will very likely pollute your tag list

**Comment by leothelocust** [comment]
That's exactly what I was wanting, thank you!
