### ISSUE TITLE
Doesn't work for member functions that do not start with keywords "public", "protected" or "private"

### ISSUE THREAD

**Issue by nguisiautien** [jb55/typescript-ctags#9]

**Comment by fedde-s** [comment]
I noticed that members listed as `readonly` are skipped. I believe that that's a manifestation of this issue.

**Comment by Eckhart-csjc** [comment]
Any plans to add support for this?

**Comment by jb55** [comment]
>Any plans to add support for this?

I will happily apply this if someone wants to implement it

**Comment by Eckhart-csjc** [comment]
Just to let everyone on this thread know, jb55 merged my pull request which addresses this.  Since the typescript syntax is so flexible, I may have missed some cases.  Please let me know if I let anything fall through the regex cracks.

**Comment by jb55** [comment]
>Just to let everyone on this thread know, jb55 merged my pull request which addresses this.  Since the typescript syntax is so flexible, I may have missed some cases.  Please let me know if I let anything fall through the regex cracks.

yup I have no way to test changes submitted to this repo, so feel free to send fixes if ya'll find any issues
